version: '3.7'
services:
  express:
    stdin_open: true
    tty: true
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - ./.env
  mongo:
    image: 'mongo:latest'
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
